### ISSUE TITLE
Weird behavior regarding Move events

### ISSUE THREAD

**Issue by doodledood** [elm-lang/mouse#4]
I basically subscribe to both `Mouse.moves` and `Mouse.ups.`

Whenever I release the mouse anywhere on the page both a `move` event and an `up` event are fired.
Whenever I release the mouse NOT on the page (like the addressbar) only an `up` event is fired.

**Comment by evancz** [comment]
These just go through to the JavaScript events behind the scenes. So I don't _think_ this is specific to Elm. The functionality here move to `elm/browser` so you can make an http://sscce.org/ if you find it there as well.
